//@api=http://127.0.0.1:3000/tasks
//@api=http://159.89.91.39:3000/tasks
@api=http://127.0.0.1:4000/ingreso


GET {{api}} HTTP/1.1

### 
GET {{api}}/47 HTTP/1.1

###   /ingreso/colaboradores
### los últimos registros por id_colaborador
GET {{api}}/colaboradores HTTP/1.1


### ultimo registro
 
GET {{api}}/ultimoregistro/2 HTTP/1.1

###
GET {{api}}/count HTTP/1.1

###
POST {{api}}
Content-Type: application/json

{
    "id_colaborador": 9,
    "ingreso":0,
    "estado":"Descanso",
    "fecha_hora":null
}

###
DELETE {{api}}/1

###

PUT {{api}}/5
Content-Type: application/json

{
    "id":44,
 "id_colaborador": 5,
  "ingreso": 1,
  "estado": "Activo"
}

