//@api=http://127.0.0.1:3000/tasks
//@api=http://159.89.91.39:3000/tasks
@api=http://127.0.0.1:3000/tasks


GET {{api}} HTTP/1.1



###


 
GET {{api}}/15 HTTP/1.1

###
GET {{api}}/count HTTP/1.1

###
POST {{api}}
Content-Type: application/json

{
    "title": "tarea para todos",
    "description": "revisión caseta"
}

###
DELETE {{api}}/8

###

PUT {{api}}/10
Content-Type: application/json

{
     "title": "tarea diez hoy ",
    "description": "description 10 10",
    "fecha": "2021-08-15T01:10:08.000Z"
}

